CREATE TABLE users (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  uuid VARCHAR NOT NULL UNIQUE,
  name  VARCHAR NOT NULL,
  email VARCHAR NOT NULL UNIQUE,
  password_digest VARCHAR NOT NULL,
  session_digest VARCHAR,
  created_at TIMESTAMP DEFAULT (DATETIME('now','localtime')) NOT NULL,
  updated_at TIMESTAMP DEFAULT (DATETIME('now','localtime')) NOT NULL
)
