[package]
name = "diesel_postgres_sample"
version = "0.1.0"
authors = ["yukihir0 <yukihiro.cotori@gmail.com>"]

[dependencies]
diesel = { version = "1.0.0", features = ["postgres"] }
dotenv = "0.9.0"
